### ISSUE TITLE
#5 figure out how to use knockout.js

### ISSUE THREAD

**Issue by yewbdar** [thaiscmky/letseat#34]

**Comment by thaiscmky** [comment]
@yewbdar I've added you to issue #15, since it's the same thing (Learning KO), assuming we're not dropping it tomorrow, I'd like you to go ahead and turn this issue into a task you'll attempt to use Knockout.js on. That way, if we decide to drop it, you've already started on something that you can easily remove Knockout.js from and continue your progress. Don't worry about understanding the entire library, just work on the task as you read/learn.

**Comment by yewbdar** [comment]
oh sorry , I created the same issue . and I plan to finish /just get idea before tomorrow afternoon .

**Comment by thaiscmky** [comment]
@yewbdar no need to apologize, just keeping you informed :)
